paperlink/paperlink/presentation/app.py
"""PaperLink

This script allows the user to make printed documents identifiable. A small 
qr code is added to every document, that will be printed out. When the user 
scans this paper document, the qr code will be identified by the program and 
the scan file can be traced back to it's original digital file. 
"""

from flask import Flask, render_template, Response, request, redirect, url_for
import os


"""id, name, path, size, type, dumped, screenshot"""

documents = [
    {"id": 0, "name": "test.py", "path": "/example/", "size": "50 MB",
        "type": "print", "dumped": 0, "screenshot": "/home/david/test.jpg"},
    {"id": 0, "name": "test.py", "path": "/example/", "size": "50 MB",
        "type": "scan", "dumped": 0, "screenshot": "/home/david/test.jpg"},
    {"id": 0, "name": "test.py", "path": "/example/", "size": "50 MB",
        "type": "print", "dumped": 0, "screenshot": "/home/david/test.jpg"},
]


app = Flask(__name__)


@app.route("/")
def index():
    return render_template("index.html")


@app.route("/all_docs")
def all_docs():
    return render_template("view_docs.html", documents=documents)


@app.route("/print_docs")
def print_docs():
    return render_template("view_docs.html", documents=documents)


@app.route("/scan_docs")
def scan_docs():
    return render_template("view_docs.html", documents=documents)


@app.route('/doc_info')
def doc_info():
    return render_template('doc_info.html')


@app.route('/trash')
def trash():
    return render_template("trash.html", documents=documents)


@app.route('/update')
def update():
    return render_template("update.html")


@app.route('/help')
def help():
    return render_template("help.html")


if __name__ == '__main__':
    app.run(debug=True)

paperlink/paperlink/presentation/routes.py
import requests
from flask import Flask, Blueprint, render_template, request

from logicfunction import logicfunc as lfunc

app = Blueprint("presentation", __name__,
                template_folder="templates",
                static_folder="static",
                static_url_path="/presentation/static")


@app.route("/")
def index():
    #lfunc.register_print_document("/media/david/Volume/Bachelorarbeit/Literatur Recherche/Bachelorarbeiten Beispiele/BA_Baulig F.pdf")
    #lfunc.register_scan_document("/media/david/Volume/Bachelorarbeit/Literatur Recherche/Bachelorarbeiten Beispiele/BA_Baulig F.pdf", "PL:2:0")
    #lfunc.get_entity_linkage_by_doc_id(1)
    #print(lfunc.get_version_history_by_doc_id(0))
    return render_template("index.html")


@app.route("/all_docs")
def all_docs():
    data = lfunc.get_all_documents_presentation()
    return render_template("view_docs.html", documents=data)


@app.route("/print_docs")
def print_docs():
    data = lfunc.get_print_documents_presentation()
    return render_template("view_docs.html", documents=data)


@app.route("/scan_docs")
def scan_docs():
    data = lfunc.get_scan_documents_presentation()
    return render_template("view_docs.html", documents=data)


@app.route('/doc_info/<int:doc_id>')
def doc_info(doc_id):
    data = lfunc.get_doc_information_presentation(doc_id)
    return render_template('doc_info.html', documents=data)


@app.route('/trash')
def trash():
    data = lfunc.get_dumped_documents_presentation()
    return render_template("trash.html", documents=data)


@app.route('/help')
def help():

    return render_template("help.html")

paperlink/paperlink/presentation/templates/doc_info.html
{% extends "extends/layout.html" %}
{% block content %}
<div class="py-5">
  <div class="container">
    <div class="row">
      <div class="col-md-12 text-center">
        <h2>Linked printed and scanned document</h2>
      </div>
    </div>
    <div class="row">
      {% set doc = documents["linkage"][0] %}
      {% include "includes/doc_card.html" %}
      <div class="col-md-4">
        <div class="col-md-12 p-3">
          <img class="link-symbol" src="{{ url_for('presentation.static', filename='img/arrow.png') }}">
        </div>
      </div>
      {% set doc = documents["linkage"][1] %}
      {% if doc != None %}
      {% include "includes/doc_card.html" %}
      {% else %}
      <div class="col-md-4 p-3 d-flex align-items-stretch">
        <div class="card box-shadow">
          <img class="card-img-top" src="{{ url_for('presentation.static', filename='img/file.png') }}">
          <div class="card-body">
            <p class="card-text" contenteditable="true">
              There is currently no linked document
            </p>
          </div>
        </div>
      </div>
      {% endif %}
    </div>
  </div>
</div>
<div class="py-5">
  <div class="container">
    <div class="row">
      <div class="col-md-12 text-center">
        <h2>Documents of the same version</h2>
      </div>
    </div>
    <div class="row">
      {% for group in documents["version"] %}
      {% set doc = group[0] %}
      {% include "includes/doc_card.html" %}
      <div class="col-md-4">
        <div class="col-md-12 p-3">
          <img class="link-symbol" src="{{ url_for('presentation.static', filename='img/arrow.png') }}">
        </div>
      </div>
      {% set doc = group[1] %}
      {% if doc != None %}
      {% include "includes/doc_card.html" %}
      {% else %}
      <div class="col-md-4 p-3 d-flex align-items-stretch">
        <div class="card box-shadow">
          <img class="card-img-top" src="{{ url_for('presentation.static', filename='img/file.png') }}">
          <div class="card-body">
            <p class="card-text" contenteditable="true">
              There is currently no linked document
            </p>
          </div>
        </div>
      </div>
      {% endif %}
      {% endfor %}
    </div>
  </div>
</div>
{% include "includes/del_modal.html" %}
{% include "includes/edit_modal.html" %}
{% endblock %}

paperlink/paperlink/presentation/templates/extends/layout.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Documentation</title>
  <meta name="description" content="">
  <meta name="keywords" content="">
  <meta name="author" content="David Sinz">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.1/css/bootstrap.min.css"
    integrity="sha384-VCmXjywReHh4PwowAiWNagnWcLhlEJLA5buUprzK8rxFgeH0kww/aWY76TfkUoSX" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
    type="text/css">
  <link rel="stylesheet" href="{{ url_for('presentation.static', filename='css/style.css') }}" type="text/css">
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="{{ url_for('presentation.index') }}">
        <i class="fa d-inline fa-lg fa-file-text-o"></i>
        &nbsp;
        <b>PaperLink</b>
      </a>
      <button class="navbar-toggler navbar-toggler-right border-0" type="button" data-toggle="collapse"
        data-target="#navbar11">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbar11">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item"> <a class="nav-link" href="{{ url_for('presentation.all_docs') }}">All Docs</a> </li>
          <li class="nav-item"> <a class="nav-link" href="{{ url_for('presentation.print_docs') }}">Printouts</a> </li>
          <li class="nav-item"> <a class="nav-link" href="{{ url_for('presentation.scan_docs') }}">Scans</a> </li>
          <li class="nav-item"> <a class="nav-link" href="{{ url_for('presentation.trash') }}">Trash</a> </li>
        </ul>
        <a class="btn btn-primary navbar-btn ml-md-2" href="{{ url_for('presentation.help') }}">Help</a>
      </div>
    </div>
  </nav>
  {% block content %}{% endblock %}
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
    integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
    integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
    crossorigin="anonymous"></script>
  <script src="{{ url_for('presentation.static', filename='js/main.js') }}"></script>
</body>

</html>

paperlink/paperlink/presentation/templates/help.html
{% extends "layout.html" %}
{% block content %}
<div class="py-3">
  <div class="container">
    <div class="row">
      <div class="col-lg-3 col-md-6 p-4">
        <h4> <b>#1</b> </h4>
        <p>A wonderful serenity has taken possession of my entire soul, like these sweet mornings.</p>
      </div>
      <div class="col-lg-3 col-md-6 p-4">
        <h4> <b>#2</b> </h4>
        <p>I am alone, and feel the charm of existence in this spot, which was created for the bliss.</p>
      </div>
      <div class="col-lg-3 col-md-6 p-4">
        <h4> <b>#3</b> </h4>
        <p>So absorbed in the exquisite sense of mere tranquil existence.</p>
      </div>
      <div class="col-lg-3 col-md-6 p-4">
        <h4> <b>#4</b> </h4>
        <p>At the present moment and yet I feel that I never was a greater artist than now.</p>
      </div>
      <div class="col-lg-3 col-md-6 p-4">
        <h4> <b>#5</b> </h4>
        <p>And the meridian sun strikes the upper surface of the impenetrable foliage.</p>
      </div>
      <div class="col-lg-3 col-md-6 p-4">
        <h4> <b>#6</b> </h4>
        <p>I throw myself down among the tall grass by the trickling stream.</p>
      </div>
      <div class="col-lg-3 col-md-6 p-4">
        <h4> <b>#7</b> </h4>
        <p>And, as I lie close to the earth, a thousand unknown plants are noticed by me.</p>
      </div>
      <div class="col-lg-3 col-md-6 p-4">
        <h4> <b>#8</b> </h4>
        <p>When I hear the buzz of the little world among the stalks, and grow familiar.</p>
      </div>
    </div>
  </div>
</div>
{% endblock %}

paperlink/paperlink/presentation/templates/includes/del_modal.html
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel"
  aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="deleteModalLabel">Delete Document?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <form id="deleteForm" action="{{ url_for('logicfunction.dump', context=request.endpoint, doc_id=0) }}" method="POST">
          <input class="btn btn-danger" type="submit" value="Delete">
        </form>
      </div>
    </div>
  </div>
</div>

paperlink/paperlink/presentation/templates/includes/doc_card.html
<div class="col-md-4 p-3 d-flex align-items-stretch">
  <div class="card box-shadow">
    <img class="card-img-top" src="{{ url_for('presentation.static', filename='img/file.png') }}">
    <div class="card-body">
      <p class="card-text" contenteditable="true">
        Name: {{ doc['name'] }}<br>
        Path: {{ doc['path'] }}<br>
        Size: {{ doc['size'] }}
      </p>
      <div class="d-flex justify-content-between align-items-center">
        <div class="btn-group">
          <a type="button" class="btn btn-sm btn-outline-secondary"
            href="{{ url_for('presentation.doc_info', doc_id=doc['id']) }}">View</a>
          <button type="button" value="{{ doc['id'] }}" class="edit-btn btn btn-sm btn-outline-secondary" data-toggle="modal"
            data-target="#editModal">Edit</button>
          <button type="button" value="{{ doc['id'] }}" class="delete-btn btn btn-sm btn-outline-secondary" data-toggle="modal"
            data-target="#deleteModal">Delete</button>
        </div>
        <small class="text-muted">
          {% if doc['type'] == "print" %}
          printout
          {% elif doc['type'] == "scan" %}
          scan
          {% endif %}
        </small>
      </div>
    </div>
  </div>
</div>

paperlink/paperlink/presentation/templates/includes/edit_modal.html
<div class="modal fade" id="editModal" tabindex="-1" role="dialog" aria-labelledby="editModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <form id="editForm" action="{{ url_for('logicfunction.update', context=request.endpoint, doc_id=0) }}"
        method="POST">
        <div class="modal-header">
          <h5 class="modal-title" id="editModalLabel">Update Document?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <input type="text" class="form-control" name="pathInputField" aria-describedby="pathHelp" placeholder="Enter path here">
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <input class="btn btn-danger" type="submit" value="Submit">
        </div>
      </form>
    </div>
  </div>
</div>

paperlink/paperlink/presentation/templates/index.html
{% extends "extends/layout.html" %}
{% block content %}
<div class="py-5 text-center"
  style="background-image: linear-gradient(to left bottom, rgba(189, 195, 199, .75), rgba(44, 62, 80, .75)); background-size: 100%;">
  <div class="container">
    <div class="row">
      <div class="mx-auto col-md-6">
        <h1>PaperLink</h1>
        <p class="mb-4">This tool will manage your printed and scanned documents. Printed documents will automatically
          be added and scanned documents can be uploaded here. Every uploaded scan shows you where the original source
          document to this scan file is located. Try it out and have fun!</p>

        <p>print</p>
        <form action="{{ url_for('logicfunction.register_print') }}" method="POST"
          class="form-inline d-flex justify-content-center">
          <div class="input-group">
            <input type="text" name="printDocPath" class="form-control" placeholder="print file path" id="form1">
            <div class="input-group-append"><button class="btn btn-primary" type="submit">Subscribe</button></div>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
<div class="py-5 text-center"
  style="background-image: linear-gradient(to left bottom, rgba(189, 195, 199, .75), rgba(44, 62, 80, .75)); background-size: 100%;">
  <div class="container">
    <div class="row">
      <div class="mx-auto col-md-6">
        <h1>PaperLink</h1>
        <p class="mb-4">This tool will manage your printed and scanned documents. Printed documents will automatically
          be added and scanned documents can be uploaded here. Every uploaded scan shows you where the original source
          document to this scan file is located. Try it out and have fun!</p>
          <p>scan</p>
        <form action="{{ url_for('logicfunction.register_scan') }}" method="POST" class="form-inline d-flex justify-content-center">
          <div class="input-group">
            <input type="text" name="scanDocPath" class="form-control" placeholder="scan" id="form1">
            <div class="input-group-append"> <button class="btn btn-primary" type="submit">Subscribe</button> </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

paperlink/paperlink/presentation/templates/trash.html
{% extends "extends/layout.html" %}
{% block content %}
{% if documents|length <= 0 %}
<div class="py-5 align-items-center d-flex">
    <div class="container py-5">
        <div class="row">
            <div class="col-md-8 px-md-5">
                <h1 class="display-3 mb-4">No documents ...</h1>
                <p class="lead mb-4">There were no documents added to the collection. Start printing documents or add
                    scan
                    documents and the collection will be extended.</p>
                <a href="{{ url_for('presentation.help') }}" class="btn btn-lg btn-primary">Help</a>
            </div>
        </div>
    </div>
</div>
{% else %}
<div class="py-4 bg-light">
    <div class="container">
        <div class="row">
            {% for doc in documents %}
            <div class="col-md-4 p-3 d-flex align-items-stretch">
                <div class="card box-shadow">
                    <img class="card-img-top" src="{{ url_for('presentation.static', filename='img/file.png') }}">
                    <div class="card-body">
                        <p class="card-text" contenteditable="true">
                            Name: {{ doc["name"] }}<br>
                            Path: {{ doc["path"] }}<br>
                            Size: {{ doc["size"] }}
                        </p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a type="button" class="btn btn-sm btn-outline-secondary"
                                    href="{{ url_for('presentation.trash', rec_id=doc['id']) }}">Recover</a>
                                <button type="button" value="{{ doc['id'] }}"
                                    class="delete-btn btn btn-sm btn-outline-secondary" data-toggle="modal"
                                    data-target="#deleteModal">Delete</button>
                            </div>
                            <small class="text-muted">
                                {% if doc["type"] == "print" %}
                                printout
                                {% elif doc["type"] == "scan" %}
                                scan
                                {% endif %}
                            </small>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endif %}
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteModalLabel">Delete Document?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <form id="deleteForm" action="{{ url_for('logicfunction.delete', doc_id=0) }}" method="POST">
                    <input class="btn btn-danger" type="submit" value="Delete">
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

paperlink/paperlink/presentation/templates/view_docs.html
{% extends "extends/layout.html" %}
{% block content %}
{% if documents|length <= 0 %}
<div class="py-5 align-items-center d-flex">
  <div class="container py-5">
    <div class="row">
      <div class="col-md-8 px-md-5">
        <h1 class="display-3 mb-4">No documents ...</h1>
        <p class="lead mb-4">There were no documents added to the collection. Start printing documents or add scan
          documents and the collection will be extended.</p>
        <a href="{{ url_for('presentation.help') }}" class="btn btn-lg btn-primary">Help</a>
      </div>
    </div>
  </div>
</div>
{% else %}
<div class="py-4 bg-light">
  <div class="container">
    <div class="row">
      {% for doc in documents %}
      {% include "includes/doc_card.html" %}
      {% endfor %}
    </div>
  </div>
</div>
{% endif %}
{% include "includes/del_modal.html" %}
{% include "includes/edit_modal.html" %}
{% endblock %}